#!/bin/sh
#
# The MIT License (MIT)
#
# Copyright (c) 2016 Sascha Vogt <sascha@vogt-neuenbuerg.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Config
DOCKER=/usr/bin/docker
DOCKER_COMPOSE=/usr/local/bin/docker-compose
DOCKER_COMPOSE_YAML=docker-compose.yml

LATEST_VERSIONS=`./get-latest-versions`


COMPOSE_HTTP_TIMEOUT=180
COMPOSE_PROJECT_NAME=versioneye

export COMPOSE_HTTP_TIMEOUT=$COMPOSE_HTTP_TIMEOUT
export COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME

for version in `echo "$LATEST_VERSIONS" | sed 's/.*\//VERSION_/' | sed 's/:/=/' | tr '[:lower:]' '[:upper:]'`; do
    eval "export $version";
    echo "export $version";
done

for image in $LATEST_VERSIONS; do
    $DOCKER pull $image
done

$DOCKER_COMPOSE -f $DOCKER_COMPOSE_YAML up -d
